version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      # specify the version you desire here
      # see https://hub.docker.com/r/circleci/node/tags/
      - image: circleci/node:8.11.2-browsers
    steps:
      - checkout
      - run:
          name: echo versions
            command: |
              node --version
              npm --version
      - run: npm install -g npm @latest
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run test -- --watch=false --progress=false --browsers=myChromeHeadless
      - run: npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js
